export const allMovies = [
  {
    adult: false,
    backdrop_path: '/417tYZ4XUyJrtyZXj7HpvWf1E8f.jpg',
    genre_ids: [16, 878, 10751],
    id: 1184918,
    original_language: 'en',
    original_title: 'The Wild Robot',
    overview:
      "After a shipwreck, an intelligent robot called Roz is stranded on an uninhabited island. To survive the harsh environment, Roz bonds with the island's animals and cares for an orphaned baby goose.",
    popularity: 5173.119,
    poster_path: '/wTnV3PCVW5O92JMrFvvrRcV39RU.jpg',
    release_date: '2024-09-12',
    title: 'The Wild Robot',
    video: false,
    vote_average: 8.672,
    vote_count: 1346,
  },
  {
    adult: false,
    backdrop_path: '/9SSEUrSqhljBMzRe4aBTh17rUaC.jpg',
    genre_ids: [878, 27],
    id: 945961,
    original_language: 'en',
    original_title: 'Alien: Romulus',
    overview:
      'While scavenging the deep ends of a derelict space station, a group of young space colonizers come face to face with the most terrifying life form in the universe.',
    popularity: 3297.462,
    poster_path: '/b33nnKl1GSFbao4l3fZDDqsMx0F.jpg',
    release_date: '2024-08-13',
    title: 'Alien: Romulus',
    video: false,
    vote_average: 7.3,
    vote_count: 1821,
  },
  {
    adult: false,
    backdrop_path: '/7h6TqPB3ESmjuVbxCxAeB1c9OB1.jpg',
    genre_ids: [27, 18, 878],
    id: 933260,
    original_language: 'en',
    original_title: 'The Substance',
    overview:
      'A fading celebrity decides to usea black market drug, a cell-replicating substance that temporarily creates a younger, better version of herself.',
    popularity: 2847.597,
    poster_path: '/lqoMzCcZYEFK729d6qzt349fB4o.jpg',
    release_date: '2024-09-07',
    title: 'The Substance',
    video: false,
    vote_average: 7.303,
    vote_count: 829,
  },
  {
    adult: false,
    backdrop_path: '/yDHYTfA3R0jFYba16jBB1ef8oIt.jpg',
    genre_ids: [28, 35, 878],
    id: 533535,
    original_language: 'en',
    original_title: 'Deadpool & Wolverine',
    overview:
      'A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him. But when his homeworld faces an existential threat, Wade must reluctantly suit-up again with an even more reluctant Wolverine.',
    popularity: 2097.211,
    poster_path: '/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg',
    release_date: '2024-07-24',
    title: 'Deadpool & Wolverine',
    video: false,
    vote_average: 7.7,
    vote_count: 4741,
  },
  {
    adult: false,
    backdrop_path: '/p5ozvmdgsmbWe0H8Xk7Rc8SCwAB.jpg',
    genre_ids: [16, 10751, 12, 35, 18],
    id: 1022789,
    original_language: 'en',
    original_title: 'Inside Out 2',
    overview:
      "Teenager Riley's mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions! Joy, Sadness, Anger, Fear and Disgust, who’ve long been running a successful operation by all accounts, aren’t sure how to feel when Anxiety shows up. And it looks like she’s not alone.",
    popularity: 1374.503,
    poster_path: '/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg',
    release_date: '2024-06-11',
    title: 'Inside Out 2',
    video: false,
    vote_average: 7.615,
    vote_count: 4443,
  },
  {
    adult: false,
    backdrop_path: '/eQEgKIRF7KeVGBQ8IYcklpU8RPf.jpg',
    genre_ids: [27, 53],
    id: 1034541,
    original_language: 'en',
    original_title: 'Terrifier 3',
    overview:
      "Five years after surviving Art the Clown's Halloween massacre, Sienna and Jonathan are still struggling to rebuild their shattered lives. As the holiday season approaches, they try to embrace the Christmas spirit and leave the horrors of the past behind. But just when they think they're safe, Art returns, determined to turn their holiday cheer into a new nightmare. The festive season quickly unravels as Art unleashes his twisted brand of terror, proving that no holiday is safe.",
    popularity: 1257.368,
    poster_path: '/63xYQj1BwRFielxsBDXvHIJyXVm.jpg',
    release_date: '2024-10-09',
    title: 'Terrifier 3',
    video: false,
    vote_average: 6.933,
    vote_count: 112,
  },
];

export const movieDetails = {
  adult: false,
  backdrop_path: '/417tYZ4XUyJrtyZXj7HpvWf1E8f.jpg',
  belongs_to_collection: {
    id: 1370345,
    name: 'The Wild Robot Collection',
    poster_path: null,
    backdrop_path: '/f6G8QPeod5ngQMs5Fe1O4LdphB7.jpg',
  },
  budget: 78000000,
  genres: [
    { id: 16, name: 'Animation' },
    { id: 878, name: 'Science Fiction' },
    { id: 10751, name: 'Family' },
  ],
  homepage: 'https://www.thewildrobotmovie.com',
  id: 1184918,
  imdb_id: 'tt29623480',
  origin_country: ['US'],
  original_language: 'en',
  original_title: 'The Wild Robot',
  overview:
    "After a shipwreck, an intelligent robot called Roz is stranded on an uninhabited island. To survive the harsh environment, Roz bonds with the island's animals and cares for an orphaned baby goose.",
  popularity: 5173.119,
  poster_path: '/wTnV3PCVW5O92JMrFvvrRcV39RU.jpg',
  production_companies: [
    {
      id: 521,
      logo_path: '/3BPX5VGBov8SDqTV7wC1L1xShAS.png',
      name: 'DreamWorks Animation',
      origin_country: 'US',
    },
  ],
  production_countries: [
    { iso_3166_1: 'US', name: 'United States of America' },
  ],
  release_date: '2024-09-12',
  revenue: 197296880,
  runtime: 102,
  spoken_languages: [
    { english_name: 'English', iso_639_1: 'en', name: 'English' },
  ],
  status: 'Released',
  tagline: 'Discover your true nature.',
  title: 'The Wild Robot',
  video: false,
  vote_average: 8.672,
  vote_count: 1346,
};
